name: finances
dependencies:
  - pip=19.1.1
  - python=3.7.3
  - pandas=0.24.2
  - plotly=3.10.0
  - Flask=1.1.1
  - conda-forge::pdfminer.six=20181108
  - conda-forge::dash=1.1.1
  - conda-forge::cufflinks-py=0.13.0
  - conda-forge::dash-table=4.1.0
  - pip:

